### ISSUE TITLE
Double quotes in a TAP query are not escaped

### ISSUE THREAD

**Issue by olebole** [django-daiquiri/daiquiri#39]
When I do a TAP query that uses double quotes (for column or table names), the response is invalid:

```
>>> import pyvo
>>> s = pyvo.dal.TAPService('https://www.plate-archive.org/tap')
>>> s.run_sync('''SELECT TOP 5 "plate_id" from applause_dr3.process;''')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyvo/dal/query.py", line 248, in execute_votable
    return votableparse(self.execute_stream().read)
  File "/usr/lib/python3/dist-packages/astropy/io/votable/table.py", line 137, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/lib/python3/dist-packages/astropy/io/votable/tree.py", line 3390, in parse
    iterator, tag, data, config, pos)
  File "/usr/lib/python3/dist-packages/astropy/io/votable/tree.py", line 3319, in _add_resource
    resource.parse(self, iterator, config)
  File "/usr/lib/python3/dist-packages/astropy/io/votable/tree.py", line 3138, in parse
    for start, tag, data, pos in iterator:
ValueError: 8:48: not well-formed (invalid token)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyvo/dal/tap.py", line 194, in run_sync
    **keywords).execute()
  File "/usr/lib/python3/dist-packages/pyvo/dal/tap.py", line 810, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl)
  File "/usr/lib/python3/dist-packages/pyvo/dal/query.py", line 251, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ValueError: 8:48: not well-formed (invalid token)
```
The reason seems to be that in the resulting VOTable, the query string is not escaped:
```
<INFO name="QUERY" value="SELECT "plate_id" from applause_dr3."process" limit 5" />
```

**Comment by jochenklar** [comment]
Fixed in f27a1404008b7df69994684ccbe9af08b9a17e8d.
